# Generated by Django 5.2.12 on 2026-03-25 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_reversed',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit at time of order', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total for this line item', max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Balance after this payment', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.branch')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipt', to='core.payment')),
            ],
        ),
    ]
