# Generated by Django 4.2.28 on 2026-04-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customerpurchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchaserequest',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpurchaserequest',
            name='converted_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_purchase_requests', to='core.order'),
        ),
    ]
